# Simple get
# Select request / command
# and press Command + Shift + P: Rest Client: Send Request
GET https://localhost:7234/api/todoitems


# Simple post
POST https://localhost:7234/api/todoitems
Content-Type: application/json

{
    "name": "muista hedelmiä"
} 



